require: rubocop-rspec

Style/StringLiterals:
      Enabled: false
Style/FrozenStringLiteralComment:
      Enabled: false
Style/ClassAndModuleChildren:
      Enabled: false
Documentation:
      Enabled: false
RSpec/MultipleExpectations:
      Max: 2
AllCops:
    NewCops: enable
    Exclude:
        - 'config/initializers/*'
        - 'config/environments/*'
        - 'config/spring.rb'
        - 'bin/*'
        - 'db/*'
        - 'db/migrate/*'
        - 'lib/tasks/*'
        - 'Gemfile'
        - 'Guardfile'
        - 'spec/rails_helper.rb'
        - 'spec/spec_helper.rb'
        - 'features/support/env.rb'
        - 'node_modules/**/*'